//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDAA1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class dangkyhocphan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dangkyhocphan()
        {
            this.lops = new HashSet<lop>();
        }

        [Display(Name = "Mã đăng ký học phần")]
        public string madkhp { get; set; }

        [Display(Name = "Học kỳ")]
        public int hocky { get; set; }

        [Display(Name = "Năm học")]
        public string namhoc { get; set; }

        [Display(Name = "Thời gian bắt đầu")]
        public System.DateTime thoigianbd { get; set; }

        [Display(Name = "Thời gian kết thúc")]
        public System.DateTime thoigiankt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lop> lops { get; set; }
    }
}
