//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDAA1
{
    using System;
    using System.Collections.Generic;
    
    public partial class file
    {
        public int idfile { get; set; }
        public string filename { get; set; }
        public string extension { get; set; }
        public string note { get; set; }
        public Nullable<int> idtb { get; set; }
    
        public virtual thongbao thongbao { get; set; }
    }
}
