//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDAA1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class khoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public khoa()
        {
            this.giangviens = new HashSet<giangvien>();
            this.lops = new HashSet<lop>();
            this.lopcns = new HashSet<lopcn>();
        }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Trống mã khoa")]
        public string makhoa { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Trống tên khoa")]
        public string tenkhoa { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Trống mã giáo viên")]
        public string magv { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<giangvien> giangviens { get; set; }
        public virtual giangvien giangvien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lop> lops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lopcn> lopcns { get; set; }
    }
}
