//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDAA1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class lopcn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lopcn()
        {
            this.sinhviens = new HashSet<sinhvien>();
        }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Trống mã lớp chủ nhiệm")]
        public string malopcn { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Trống mã giảng viên")]
        public string magv { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Trống mã khoa")]
        public string makhoa { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Trống mã niên khóa")]
        public int nienkhoa { get; set; }

        public virtual giangvien giangvien { get; set; }
        public virtual khoa khoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sinhvien> sinhviens { get; set; }
    }
}
