//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDAA1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyDatabaseEntities9 : DbContext
    {
        public MyDatabaseEntities9()
            : base("name=MyDatabaseEntities9")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dangkyhocphan> dangkyhocphans { get; set; }
        public virtual DbSet<hoc> hocs { get; set; }
        public virtual DbSet<khoa> khoas { get; set; }
        public virtual DbSet<lop> lops { get; set; }
        public virtual DbSet<lopcn> lopcns { get; set; }
        public virtual DbSet<mon> mons { get; set; }
        public virtual DbSet<taikhoan> taikhoans { get; set; }
        public virtual DbSet<giangvien> giangviens { get; set; }
        public virtual DbSet<sinhvien> sinhviens { get; set; }
        public virtual DbSet<thongbao> thongbaos { get; set; }
    }
}
