//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDAA1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class mon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mon()
        {
            this.lops = new HashSet<lop>();
        }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Trống mã môn")]
        public string mamon { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Trống tên môn")]
        public string tenmon { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Trống hệ số giữa kỳ")]
        public double hsgk { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Trống hệ số cuối kỳ")]
        public double hsck { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Trống số tiết")]
        public int sotiet { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Trống số tính chỉ")]
        public int sotc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lop> lops { get; set; }
    }
}
