//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDAA1
{
    using System;
    using System.Collections.Generic;
    
    public partial class mon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mon()
        {
            this.lops = new HashSet<lop>();
            this.mon1 = new HashSet<mon>();
        }
    
        public int idmon { get; set; }
        public string tenmon { get; set; }
        public string mamon { get; set; }
        public Nullable<int> idmontruoc { get; set; }
        public Nullable<double> hsqt { get; set; }
        public Nullable<double> hsth { get; set; }
        public Nullable<double> hsgk { get; set; }
        public Nullable<double> hsck { get; set; }
        public Nullable<int> sotc { get; set; }
        public Nullable<int> tclt { get; set; }
        public Nullable<int> tcth { get; set; }
        public string tenvama { get { return tenmon + "-" + mamon; } }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lop> lops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mon> mon1 { get; set; }
        public virtual mon mon2 { get; set; }
    }
}
