//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDAA1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class sinhvien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sinhvien()
        {
            this.giangdays = new HashSet<giangday>();
            this.taikhoans = new HashSet<taikhoan>();
        }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Trống mã sinh viên")]
        public string masv { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Trống họ tên")]
        public string hoten { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Trống giới tính")]
        public string gioitinh { get; set; }
        public System.DateTime ngaysinh { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Trống mã lớp chủ nhiệm")]
        public string malopcn { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Trống địa chỉ")]
        public string diachi { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Trống quê quán")]
        public string quequan { get; set; }

        [Required(ErrorMessage = "You must provide a phone number")]
        [Display(Name = "Home Phone")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Sai định dạng số điện thoại")]
        public string sdt { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Trống bậc học")]
        public string bachoc { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<giangday> giangdays { get; set; }

        public virtual lopcn lopcn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<taikhoan> taikhoans { get; set; }
    }
}
