//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDAA1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class taikhoan
    {
        [Required(AllowEmptyStrings = false, ErrorMessage = "Trống mã tài khoản")]
        public string matk { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Trống mật khẩu")]
        public string password { get; set; }

        public string masv { get; set; }
        public string magv { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Trống nhóm")]
        public string nhom { get; set; }

        public virtual giangvien giangvien { get; set; }
        public virtual sinhvien sinhvien { get; set; }
    }
}
