//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDAA1
{
    using System;
    using System.Collections.Generic;
    
    public partial class thongbao
    {
        public int matb { get; set; }
        public string matk { get; set; }
        public string tag { get; set; }
        public string noidung { get; set; }
        public string tieude { get; set; }
        public System.DateTime thoigiandang { get; set; }
    
        public virtual taikhoan taikhoan { get; set; }
    }
}
