//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDAA1
{
    using System;
    using System.Collections.Generic;
    
    public partial class thongbao
    {
        public int idtb { get; set; }
        public string tieude { get; set; }
        public string noidung { get; set; }
        public string tag { get; set; }
        public Nullable<int> idtk { get; set; }
        public string file { get; set; }
        public Nullable<System.DateTime> thoigiandang { get; set; }
        public Nullable<System.DateTime> thoigiancapnhat { get; set; }
    
        public virtual taikhoan taikhoan { get; set; }
    }
}
