//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDAA1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dangkyhocphan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dangkyhocphan()
        {
            this.lops = new HashSet<lop>();
        }
    
        public string madkhp { get; set; }
        public int hocky { get; set; }
        public string namhoc { get; set; }
        public Nullable<System.DateTime> thoigianbd { get; set; }
        public Nullable<System.DateTime> thoigiankt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lop> lops { get; set; }
    }
}
